name: Deploy to Deta
on:
  - push
  - workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Push code to deta
        uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: 'confess'
          deta-project: 'confess'
          deta-project-dir: '.'
      
      - name: Install cli and install
        shell: bash
        run: |
          curl -fsSL https://get.deta.dev/cli.sh | sh

      - name: Deploy .env file
        shell: bash  
        run: |
          touch .env
          echo "DETA_PROJECT_KEY=${{ secrets.DETA_PROJECT_KEY }}" >> .env
          echo "SECRET_KEY"=${{ secrets.SECRET_KEY }} >> .env
          deta update -e .env